on: [push]

jobs:
  kicad_job:
    runs-on: ubuntu-latest
    name: DRC Report
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run KiCad DRC
        id: drc
        uses: sparkengineering/kicad-action@v2
        if: '!cancelled()'
        with:
          kicad_pcb: playpen-hw.kicad_pcb
          pcb_drc: true

      # Upload DRC report only if DRC failed
      - name: Upload DRC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.drc.conclusion == 'failure' }}
        with:
          name: drc.rpt
          path: ${{ github.workspace }}/drc.rpt