on: [push]

jobs:
  kicad_job:
    runs-on: ubuntu-latest
    name: ERC Report
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v2
        if: '!cancelled()'
        with:
            kicad_sch: playpen-hw.kicad_sch
            sch_erc: true


      # Upload ERC report only if ERC failed
      - name: Upload ERC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.erc.conclusion == 'failure' }}
        with:
          name: erc.rpt
          path: ${{ github.workspace }}/erc.rpt